import {useEffect,useRef,useState} from 'react';
import {tales,creatures,journalFor,canAccept,taleProgress} from './encounters';
import {gear,tierFor,equipped} from './equipment';
import {GearArt,CreatureArt} from './Armory';
import {regions,fmt} from './catalog';

export function FieldNotes({state,region,taleId,onSelectTale,onStrike,onRetry,onAccept,onListen,onClaim,onComic}){
 const [libraryFilter,setLibraryFilter]=useState('all');
 const journal=journalFor(state),tale=tales[taleId],creature=creatures[region],battle=journal.battles[region],quest=journal.quests[taleId],locked=region>=state.frontier;
 const library=tales.filter(t=>libraryFilter==='all'||(libraryFilter==='bonus'?t.episode===3:journal.comics.includes(t.id)));
 return <section className="field-notes" aria-label="音乐小怪兽与奇闻" style={{'--region-accent':creature.color}}>
 <header><div><p className="eyebrow">FIELD NOTES / 世界海奇闻录</p><h2>六种相遇，二十四段远行。</h2></div><span className="capsule">{journal.comics.length} / {tales.length} 漫画已收藏</span></header>
 <div className="bestiary-strip" aria-label="奇闻生物图鉴">{creatures.map((c,i)=><button key={c.name} className={region===i?'selected':''} onClick={()=>onSelectTale(i)} aria-label={'查阅'+c.name+'奇闻'} aria-pressed={region===i}><CreatureArt region={i}/><b>{c.name}</b><small>{i<state.frontier?c.style:'迷雾中的相遇'}</small></button>)}</div>
 <div className="encounter-layout"><article className="monster-sheet"><div className="monster-portrait"><CreatureArt region={region}/><span>NO. {String(region+1).padStart(2,'0')} / {regions[region].name}</span><small>{creature.style}</small></div><div className="monster-copy"><p className="eyebrow">{locked?'迷雾中尚未发现':battle?.won?'已共鸣 / 支线开放':'WILD ENCOUNTER / 音乐小怪兽'}</p><h3>{creature.name}</h3><p>{locked?'解锁这片海域后，就能遇见它。':creature.description}</p><div className="battle-meters"><label>小怪兽共鸣值 <b>{battle?.enemy??creature.hp}/{creature.hp}</b><progress max={creature.hp} value={battle?.enemy??creature.hp}/></label><label>骑士体力 <b>{battle?.hp??60}/60</b><progress max="60" value={battle?.hp??60}/></label></div><p className="battle-log" role="status">{battle?.log||('已装备 '+equipped(state,'weapon').name+' / '+equipped(state,'shield').name+'。回声斩强攻，守拍减伤。')}</p><div className="encounter-actions">{battle?.won?<span className="capsule">已交战 · +90 XP 已入账</span>:battle?.hp===0?<button onClick={onRetry}>重新调音 · 再次挑战</button>:<><button disabled={locked} onClick={()=>onStrike('echo')}>回声斩</button><button disabled={locked} className="secondary" onClick={()=>onStrike('guard')}>守拍</button></>}</div></div></article>
 <article className="tale-sheet"><div className="episode-tabs" aria-label="区域故事章节">{[0,1,2,3].map(e=>{const id=region+e*6;return <button key={e} aria-pressed={tale.episode===e} onClick={()=>onSelectTale(id)}>{['初遇','回响','终章','番外'][e]}{journal.quests[id]?.status==='claimed'?' · 完成':''}</button>;})}</div><p className="eyebrow">SIDE STORY {String(taleId+1).padStart(2,'0')} / {tale.style||creature.style}</p><h3>{tale.title}</h3><p className="tale-story">{locked?'故事还藏在迷雾里，等待你的第一步。':tale.story}</p><div className="quest-instruction"><span>{quest?.status==='claimed'?'已完成':quest?.status==='ready'?'旋律收集完成':quest?'正在寻声':'支线任务'}</span><strong>{tale.quest}</strong><small>接取后有效聆听 {tale.target} {tale.kind==='genres'?'种不同流派':tale.kind==='albums'?'张不同专辑':'首音乐'} · {tale.genres.join(' / ')}。20 秒，短曲需听满 80%。</small>{quest&&<div className="quest-progress"><progress max={tale.target} value={Math.min(tale.target,taleProgress(tale,quest))}/><b>{Math.min(tale.target,taleProgress(tale,quest))} / {tale.target}</b></div>}</div>{quest?.track&&<p className="found-track">最近找到的声音：{quest.track.title}</p>}<div className="encounter-actions">{!quest?<button disabled={!canAccept(state,taleId)} onClick={()=>onAccept(taleId)}>{locked?'先解锁海域':!battle?.won?'交战获胜后接取':tale.episode&&!canAccept(state,taleId)?'完成上一章后开放':'接取支线任务'}</button>:quest.status==='active'?<button onClick={()=>onListen(taleId)}>前往聆听任务曲目</button>:quest.status==='ready'?<button onClick={()=>onClaim(taleId)}>完成奇闻 · 漫画 +{tale.xp} XP</button>:<button onClick={()=>onComic(taleId)}>阅读已收藏漫画</button>}</div><p className="tale-footnote">奖励：漫画章节 1 张 / {tale.xp} XP / {tale.episode+1} 碎片{tale.episode===2?' / 区域专属装备':''}</p></article></div>
 <div id="comic-collection" className="comic-library"><header><div><p className="eyebrow">MY COMIC COLLECTION / 我的漫画册</p><h3>每段旅途，都有一页可收藏。</h3></div><div className="episode-tabs"><button aria-pressed={libraryFilter==='all'} onClick={()=>{setLibraryFilter('all');document.getElementById('comic-collection')?.scrollIntoView({behavior:'smooth',block:'start'});}}>全部章节 {tales.length}</button><button aria-pressed={libraryFilter==='owned'} onClick={()=>{setLibraryFilter('owned');document.getElementById('comic-collection')?.scrollIntoView({behavior:'smooth',block:'start'});}}>已收藏 {journal.comics.length}</button><button aria-pressed={libraryFilter==='bonus'} onClick={()=>{setLibraryFilter('bonus');document.getElementById('comic-collection')?.scrollIntoView({behavior:'smooth',block:'start'});}}>新番外 6</button></div></header><div className="comic-grid">{library.map(t=>{const owned=journal.comics.includes(t.id);return <button className={owned?'owned':'unowned'} key={t.id} onClick={()=>owned?onComic(t.id):onSelectTale(t.id)} aria-label={(owned?'阅读漫画':'查看支线')+t.title}><img src={t.art} alt="" loading="lazy"/><span className="comic-tag">{owned?'已收藏':t.region>=state.frontier?'海域未解锁':'待探索'}</span><div><small>{regions[t.region].name} / 第 {t.episode+1} 章</small><strong>{t.title}</strong><p>{t.style||creatures[t.region].style}</p></div></button>;})}</div>{!library.length&&<p className="library-empty">还没有收藏。与一位小怪兽交战，开始第一段奇闻。</p>}</div>
 </section>;
}
function Modal({open,onClose,label,className,children}){const ref=useRef(null);useEffect(()=>{if(open&&!ref.current.open)ref.current.showModal();if(!open&&ref.current.open)ref.current.close();},[open]);return <dialog ref={ref} className={className} aria-label={label} onCancel={onClose} onClose={onClose}><button className="folio-close" onClick={onClose} aria-label="关闭卡片">关闭</button>{children}</dialog>;}
export function HarvestCard({open,onClose,state,onExplore}){
 const r=state.receipt;if(!r)return null;const tier=tierFor(r.total),loot=r.loot||{title:'探索收获',art:'/assets/harvest-engraving.png',keys:1,upgrade:1,shards:0,item:null,story:'你带着唱片的记忆归航，灯塔为旅人点亮。'},item=gear.find(g=>g.id===loot.item);
 return <Modal open={open} onClose={onClose} label="每日探索收获卡" className={'harvest-dialog harvest-'+tier.id}><div className="harvest-art"><img src={loot.art} alt={loot.title+'探索插画'}/>{<div className="harvest-art-title"><span>SONORA / FIELD JOURNAL</span><h2>{loot.title}</h2><p>{tier.id==='legend'?'A SONG AMONG THE STARS':'A MEMORY FROM THE SEA'}</p></div>}</div><div className="harvest-content"><p className="eyebrow">EXPEDITION / {r.day||state.day}</p><span className="reward-tier-label">{loot.title} / {tier.min} XP+</span><h3>听见更远的世界，<br/>带回不同的收获。</h3><p className="harvest-flavor">{loot.story} 本次记录 {r.tracks} 段音乐与 {r.cds} 张唱片。</p><div className="harvest-xp">+{fmt(r.total)} <span>XP</span></div>{item&&<div className="reward-gear"><GearArt item={item}/><div><small>NEW EQUIPMENT / {item.rarity}</small><strong>{item.name}</strong><p>{item.description}</p></div></div>}<div className="loot-items"><div><b>强化等级</b><span>+{loot.upgrade} → +{r.equipment}</span><small>强化碎片 +{loot.shards}{!item&&r.loot?' · 重复装备已转化':''}</small></div><div><b>探索钥匙</b><span>+{loot.keys} KEY</span><small>开启新的迷雾海域</small></div><div><b>骑士等级</b><span>LV.{r.oldLevel} → LV.{r.newLevel}</span><small>{fmt(r.damage)} 点边界攻击</small></div></div><details><summary>查看经验结算明细</summary><dl><div><dt>有效聆听</dt><dd>+{r.listen}</dd></div><div><dt>查阅唱片</dt><dd>+{r.browse}</dd></div><div><dt>新流派发现</dt><dd>+{r.discovery}</dd></div><div><dt>装备额外回馈</dt><dd>+{r.bonus||0}</dd></div></dl></details><button className="harvest-continue" onClick={onExplore}>收好战利品 · 继续探索</button><small className="saved-note">今日收获已保存 · 新装备可在首页选择 · 再次查看不会重复领取</small></div></Modal>;
}
export function ComicCard({id,onClose}){const tale=id!==null?tales[id]:null;return <Modal open={!!tale} onClose={onClose} label="奇闻漫画收藏卡" className="comic-dialog">{tale&&<><img src={tale.art} alt={(tale.style||creatures[tale.region].style)+'音乐冒险漫画，'+tale.title}/><div className="comic-caption"><p className="eyebrow">SONORA TALES / VOL. {String(id+1).padStart(2,'0')} / 第 {tale.episode+1} 章</p><h2>{tale.title}</h2><p>{tale.ending}</p><small>支线奖励已计入 · +{tale.xp} XP · {tale.episode+1} 碎片{tale.episode===2?' · 区域专属装备':''} · 可随时重读</small></div></>}</Modal>;}
