export const genrePages=[
 {id:'jazz',name:'爵士',en:'JAZZ',origin:'新奥尔良 / 多重传统相遇',color:'#9b713c',album:'A-004',summary:'从非裔美国社群的音乐实践出发，爵士吸收蓝调、拉格泰姆与铜管乐队传统。即兴不是随意演奏，而是在共同语言中给出自己的回答。',listen:'先听鼓与贝斯如何摆动，再追踪独奏与乐队的呼应。',timeline:[['1890s–1910s','新奥尔良的乐队与即兴','城市的社群、游行和舞会孕育早期爵士。'],['1930s–1940s','摇摆与大乐队','编曲、舞蹈节奏和独奏共同塑造流行声音。'],['1940s 起','Bebop 等新的探索','更复杂的即兴与节奏，拓宽聆听的边界。']],sources:[['美国国家公园管理局：爵士起源','https://www.nps.gov/jazz/learn/historyculture/history_early.htm']]},
 {id:'rock',name:'摇滚',en:'ROCK',origin:'节奏蓝调 / 吉他与青年文化',color:'#9c5141',album:'A-028',summary:'摇滚不是凭空出现的新声音。早期摇滚把节奏蓝调、乡村等传统重新组合，电吉他的音色与鲜明节拍逐渐成为重要表达。',listen:'听吉他重复段、鼓的重拍，以及歌曲如何积蓄和释放能量。',timeline:[['早期根系','蓝调与节奏蓝调','声音传统和演奏方式为早期摇滚提供土壤。'],['1950s','Chuck Berry 等人的创造','吉他乐句、节奏与叙事一起塑造新的歌曲语言。'],['此后','更多摇滚分支','这里以馆藏人物作为入口，不把全部摇滚写成一条单线。']],sources:[['摇滚名人堂：Chuck Berry','https://rockhall.com/inductees/chuck-berry/'],['摇滚名人堂：蓝调根系','https://oldschool-edu.rockhall.com/sites/default/files/2018-10/Blues%20Roots%20Playlist.pdf']]},
 {id:'soul',name:'灵魂与放克',en:'SOUL / FUNK',origin:'福音 / 情感 / 律动',color:'#876335',album:'A-181',summary:'灵魂乐强调富有张力的人声表达；放克把节奏推到前景，让乐队各声部共同编织律动。两者相连，但不能简单视为同一个流派。',listen:'听主唱的呼喊与回应，再把注意力转向贝斯、鼓和节奏吉他。',timeline:[['声音根系','福音的情感表达','James Brown 将福音表达转化为世俗舞台语言。'],['舞台演变','灵魂歌手与身体律动','歌唱、动作与乐队回应共同推动歌曲情绪。'],['放克发展','节奏成为结构核心','更精简、强调律动的合奏影响许多后来音乐。']],sources:[['Smithsonian：James Brown','https://www.si.edu/spotlight/james-brown']]},
 {id:'hiphop',name:'嘻哈',en:'HIP HOP',origin:'布朗克斯 / DJ 与社区',color:'#6d587a',album:'A-126',summary:'嘻哈不只是说唱歌曲，也是围绕 DJ、舞蹈、视觉表达与语言形成的文化。它的早期发展与纽约布朗克斯的社区生活紧密相连。',listen:'听采样如何被重新组织，以及说唱的节奏怎样与鼓点对话。',timeline:[['1970s','布朗克斯的文化场景','社区派对与创意实践孕育新的音乐文化。'],['1979 起','唱片记录与传播','录音把原本的现场实践带给更多听众。'],['后来','不断扩展的表达','地方声音与当代作品持续改写这门文化的面貌。']],sources:[['Smithsonian：Hip-Hop in the Bronx','https://nmaahc.si.edu/explore/stories/hip-hop-bronx'],['Smithsonian：嘻哈与说唱选集','https://nmaahc.si.edu/explore/publications/smithsonian-anthology-hip-hop-and-rap']]},
 {id:'electronic',name:'电子',en:'ELECTRONIC',origin:'音源实验 / 合成器 / 鼓机',color:'#4d7972',album:'A-214',summary:'电子音乐是广阔的声音家族，而非一种固定节奏。振荡器、合成器和鼓机使创作者能直接设计音色，也改变了音乐的制作方法。',listen:'试着区分节拍与音色：一种声音是敲击、采样，还是合成得到的？',timeline:[['早期实验','机械与电子音源','不用传统乐器，也能寻找新的声音与节奏。'],['鼓机时代','可编程的节拍','音乐家可以组合、重复并改变节奏模式。'],['1980s 等时期','TB-303 与 House','鼓机和电子音色参与舞池音乐的发展。']],sources:[['英国科学博物馆：寻找节拍','https://blog.sciencemuseum.org.uk/in-search-of-the-beat/']]},
 {id:'reggae',name:'雷鬼',en:'REGGAE',origin:'牙买加 / 社区与声音系统',color:'#71824a',album:'A-280',summary:'雷鬼在牙买加多种音乐影响的交汇中形成。Ska、Rocksteady 与 Reggae 的变化既是节奏变化，也与当地文化和生活相连。',listen:'留意反拍的吉他或键盘，以及低音如何托住整首歌。',timeline:[['1960s 初','Ska','活跃的节奏和当地流行音乐场景。'],['1960s 中','Rocksteady','Ska 的速度放缓，人声与低音更突出。'],['1960s 末起','Reggae','新的节奏语言逐渐形成，并走向世界。']],sources:[['UNESCO：牙买加雷鬼','https://www.unesco.org/archives/multimedia/document-4760'],['牙买加政府信息署：雷鬼发展','https://jis.gov.jm/jamaica/legendary-reggae-music-born-in-jamaica/']]},
 {id:'folk',name:'民谣',en:'FOLK',origin:'传统传唱 / 记录 / 再创作',color:'#927744',album:'A-247',summary:'民谣不只指木吉他歌曲。传统传唱、社群记忆与后来的创作歌手都是不同入口。本页以美国民谣复兴的记录为例，并不代表全球民间音乐的唯一历史。',listen:'听歌词讲述谁的生活，伴奏如何为叙事留下空间。',timeline:[['传统传承','歌曲在社群中流动','口传与演唱把故事交给下一位歌者。'],['1940s–1950s','记录与分享','Pete Seeger、Folkways 等人保存和传播歌曲。'],['1950s 末等时期','民谣复兴','新的听众和创作实践重新连接传统。']],sources:[['Smithsonian Folkways：Pete Seeger','https://folkways.si.edu/artists/pete-seeger'],['Smithsonian Folkways：使命与历史','https://folkways.si.edu/mission-and-history']]},
 {id:'ambient',name:'环境音乐',en:'AMBIENT',origin:'声音 / 空间 / 注意力',color:'#58778a',album:'A-236',summary:'环境音乐关注声音怎样改变空间与注意力，而不必让明确旋律或强烈节拍始终占据中心。Brian Eno 的作品为这一思路提供了重要入口。',listen:'听声音之间的空隙、缓慢变化，以及它和周围环境的关系。',timeline:[['1975','Discreet Music','重复、系统与空间感成为探索的重要部分。'],['1978','Music for Airports','以机场空间为出发点，阐释环境音乐的想法。'],['1982','On Land','继续探索声音与想象中的景观。']],sources:[['UMe 官方再版资料与 Eno 原始说明','https://www.prnewswire.com/news-releases/brian-eno---discreet-music---music-for-films---music-for-airports---on-land-300724141.html']]},
];
export const handbookFor=s=>({page:0,bookmarks:[],stamps:{},notes:{},...s.handbook});
export function turnPage(s,page){if(!Number.isInteger(page)||page<0||page>=genrePages.length)return s;const h=handbookFor(s);if(h.page===page)return s;return {...s,handbook:{...h,page}};}
export function bookmarkPage(s,id){if(!genrePages.some(p=>p.id===id))return s;const h=handbookFor(s);return {...s,handbook:{...h,bookmarks:h.bookmarks.includes(id)?h.bookmarks.filter(x=>x!==id):[...h.bookmarks,id]}};}
export function stampPage(s,id,x=.74,y=.72,ink='rust'){if(!genrePages.some(p=>p.id===id)||!Number.isFinite(x)||!Number.isFinite(y)||!['rust','green','blue'].includes(ink))return s;const h=handbookFor(s);return {...s,handbook:{...h,stamps:{...h.stamps,[id]:{x:Math.max(.1,Math.min(.9,x)),y:Math.max(.1,Math.min(.9,y)),ink,date:s.day}}}};}
export function notePage(s,id,text){if(!genrePages.some(p=>p.id===id)||typeof text!=='string')return s;const h=handbookFor(s);return {...s,handbook:{...h,notes:{...h.notes,[id]:text.slice(0,240)}}};}
