import {useState} from 'react';
import {soundReport} from './soundHistory';
export function SoundLandscape({state,playing=false}){
 const [range,setRange]=useState('today'),[selected,setSelected]=useState('harbor'),[paused,setPaused]=useState(false);
 function changeRange(next){setRange(next);document.getElementById('sound-landscape')?.scrollIntoView({behavior:'smooth',block:'start'});}
 const report=soundReport(state,range),region=report.regions.find(r=>r.id===selected)||report.regions[0];
 const records=selected==='other'?report.other:report.records.filter(t=>region.genres.includes(t.genre));
 const genres=Object.entries(report.genres).filter(([genre])=>selected==='other'?!report.regions.some(r=>r.genres.includes(genre)):region.genres.includes(genre)).sort((a,b)=>b[1]-a[1]);
 return <section id="sound-landscape" className={'sound-landscape '+(playing&&!paused?'sound-playing':'')+(paused?' sound-paused':'')} aria-label="聆听风格地形记录">
  <header className="landscape-heading"><div><p className="eyebrow">05 / THE SHAPE OF YOUR LISTENING</p><h2>听过的声音，长成一片旷野。</h2><p>六种声音地形，收集你真正听见的频率。</p></div><div className="landscape-controls"><div className="landscape-range" aria-label="聆听记录时间范围"><button aria-pressed={range==='today'} onClick={()=>changeRange('today')}>今日</button><button aria-pressed={range==='all'} onClick={()=>changeRange('all')}>累计</button></div><button className="landscape-pause" aria-pressed={paused} onClick={()=>setPaused(v=>!v)}>{paused?'恢复动态':'暂停动态'}</button></div></header>
  <div className="landscape-summary"><span><b>{report.total.toString().padStart(2,'0')}</b> 达标聆听记录</span><span><b>{report.genreCount.toString().padStart(2,'0')}</b> 音乐流派</span><span><b>{report.days.toString().padStart(2,'0')}</b> 有记录的日子</span><small>{report.total?'你的声音标本已保存':'还没有记录，真实聆听会点亮这里'}</small></div>
  <div className="terrain-deck" aria-label="六片音乐风格地形">{report.regions.map((r,i)=>{const height=r.count/report.max*60;return <button key={r.id} className={'terrain-station '+(selected===r.id?'selected':'')+(r.count?' has-records':'')} aria-pressed={selected===r.id} aria-label={r.name+'，'+r.count+'条达标聆听记录'} onClick={()=>setSelected(r.id)} style={{'--terrain-color':r.color,'--lift':height+'px','--float-delay':i*-.7+'s'}}><span className="terrain-index">0{i+1} / {r.label}</span><div className="terrain-stage"><span className="terrain-shadow"/><span className="terrain-support" style={{height:height+'px'}}/><span className="terrain-art" aria-hidden="true" style={{backgroundPosition:`${i%3*50}% ${Math.floor(i/3)*100}%`}}/><span className="terrain-count">{r.count}</span></div><strong>{r.name}</strong><span className="terrain-count-label">{r.count?'RECORDS / 已采集':'AWAITING SOUND / 待聆听'}</span><span className="terrain-meter"><i style={{width:r.count/report.max*100+'%'}}/></span></button>;})}</div>
  <div className="landscape-detail"><div><p className="eyebrow">SOUND SPECIMENS / 声音标本</p><h3>{selected==='other'?'本地与其他频率':region.name} <span>{records.length} 条</span></h3><div className="landscape-genres">{genres.length?genres.map(([genre,count])=><span key={genre}>{genre}<b>{count}</b></span>):<p>还没有这类达标聆听，去装载一张唱片吧。</p>}</div></div><details><summary>查阅曲目记录 {records.length}</summary><ul>{records.map(t=><li key={t.day+'/'+t.id}><span>{t.title}<small>{t.genre} / {t.albumCode}</small></span><time>{t.day}</time></li>)}</ul>{!records.length&&<p>当前范围暂无记录。</p>}</details>{report.other.length>0&&<button className="other-sounds" aria-pressed={selected==='other'} onClick={()=>setSelected('other')}>本地 / 其他频率 {report.other.length}</button>}</div>
  <footer className="landscape-note"><span>每首每日首次达标记 1 条；20 秒或短曲 80%，重复播放不增加同日记录。</span><span>柱高与进度条按当前范围数量相对缩放 · 地形插画为风格装饰</span><span>累计从本版起保存，仅能补入现存的当日记录。</span></footer>
 </section>;
}
